---
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ${COMPOSE_DIR}/monitoring/prometheus:/etc/prometheus
      - ${DOCKER_DIR}/monitoring/prometheus:/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ${DOCKER_DIR}/monitoring/grafana:/var/lib/grafana 
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command: "--path.rootfs=/host"
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - ${NODE_EXPORTER_PORT}:9100
    restart: unless-stopped
